services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=realworld
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password